/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterShopIdRouteImport } from './routes/register/$shopId'
import { Route as QueueShopIdRouteImport } from './routes/queue/$shopId'
import { Route as BizShopIdRouteImport } from './routes/biz/$shopId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterShopIdRoute = RegisterShopIdRouteImport.update({
  id: '/register/$shopId',
  path: '/register/$shopId',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueShopIdRoute = QueueShopIdRouteImport.update({
  id: '/queue/$shopId',
  path: '/queue/$shopId',
  getParentRoute: () => rootRouteImport,
} as any)
const BizShopIdRoute = BizShopIdRouteImport.update({
  id: '/biz/$shopId',
  path: '/biz/$shopId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/biz/$shopId': typeof BizShopIdRoute
  '/queue/$shopId': typeof QueueShopIdRoute
  '/register/$shopId': typeof RegisterShopIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/biz/$shopId': typeof BizShopIdRoute
  '/queue/$shopId': typeof QueueShopIdRoute
  '/register/$shopId': typeof RegisterShopIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/biz/$shopId': typeof BizShopIdRoute
  '/queue/$shopId': typeof QueueShopIdRoute
  '/register/$shopId': typeof RegisterShopIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/terms'
    | '/biz/$shopId'
    | '/queue/$shopId'
    | '/register/$shopId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/terms'
    | '/biz/$shopId'
    | '/queue/$shopId'
    | '/register/$shopId'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/terms'
    | '/biz/$shopId'
    | '/queue/$shopId'
    | '/register/$shopId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  BizShopIdRoute: typeof BizShopIdRoute
  QueueShopIdRoute: typeof QueueShopIdRoute
  RegisterShopIdRoute: typeof RegisterShopIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/$shopId': {
      id: '/register/$shopId'
      path: '/register/$shopId'
      fullPath: '/register/$shopId'
      preLoaderRoute: typeof RegisterShopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue/$shopId': {
      id: '/queue/$shopId'
      path: '/queue/$shopId'
      fullPath: '/queue/$shopId'
      preLoaderRoute: typeof QueueShopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biz/$shopId': {
      id: '/biz/$shopId'
      path: '/biz/$shopId'
      fullPath: '/biz/$shopId'
      preLoaderRoute: typeof BizShopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  BizShopIdRoute: BizShopIdRoute,
  QueueShopIdRoute: QueueShopIdRoute,
  RegisterShopIdRoute: RegisterShopIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
